version: '3.8'
services:

  # Use root/root as user/password credentials
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - "./scripts/init.sql:/docker-entrypoint-initdb.d/1.sql"    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080